### PR TITLE
Fix license url with `/blob` path prefix

### PR DESCRIPTION
**Pull request by SimonMarquis**

### CODE REVIEW

**Comment by martinbonnin** [comment]
Ah thanks! I was always curious if people actually use this for real. Do you use [licensee](https://github.com/cashapp/licensee) or some other automatic way to detect the license?

**Comment by SimonMarquis** [comment]
No, not really, but the links used in search engines are broken 🤷

- https://mvnrepository.com/artifact/net.mbonnin.xoxo/xoxo/0.2
- https://search.maven.org/artifact/net.mbonnin.xoxo/xoxo/0.2/jar

**Comment by martinbonnin** [comment]
Good catch 🙏

**Comment by SimonMarquis** [comment]
I think [licensee](https://github.com/cashapp/licensee) uses the license name.
Though [Google's OSS plugin](https://developers.google.com/android/guides/opensource) might use the url.

**Pull request merged**
